[package]
name = "stylish_webrender"
version = "0.1.0"
authors = ["Matthew Collins <thethinkofdeath@gmail.com>"]

[[bin]]
name = "stylish_webrender"
doc = false

[dependencies]
stylish = { path = "../" }
gleam = "0.4.3"
app_units = "0.4"
stb_truetype = "0.2.1"

[dev-dependencies]
sdl2 = "0.30.0"
image = "0.13.0"

[dependencies.webrender]
git = "https://github.com/servo/webrender"
rev = "568c727b73"
default-features = false
features = [ "freetype-lib" ]

[dependencies.webrender_traits]
git = "https://github.com/servo/webrender"
rev = "568c727b73"
default-features = false
features = []