language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

addons:
  apt:
    packages:
      - libsdl2-2.0-0
      - libsdl2-dev
script:
  - cargo build --all
  - cargo test --all